name: fieldapp
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies: 
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  http: ^0.13.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.0.9
  im_stepper: ^0.1.3
  internet_connection_checker: ^0.0.1+4
  get: 4.6.5
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  timelines: ^0.1.0
  geolocator: ^10.1.0
  maps_launcher: ^2.2.0
    
  flutter: 
    sdk: flutter

  
  

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  fonts: 
    - family: Mulish-Regular
      fonts: 
        - asset: assets/fonts/Mulish-Regular.ttf
    - family: Mulish-ExtraBold
      fonts: 
        - asset: assets/fonts/Mulish-ExtraBold.ttf
    - family: FiraSans-Regular
      fonts: 
        - asset: assets/fonts/FiraSans-Regular.ttf
    - family: FiraSans-ExtraBold
      fonts: 
        - asset: assets/fonts/FiraSans-ExtraBold.ttf
    - family: FiraSans-Medium
      fonts: 
        - asset: assets/fonts/FiraSans-Medium.ttf
  uses-material-design: true

